---
title: "Early Years Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)

```

```{r}
health_board_id <- read_csv(here("data_clean/health_board_id.csv"))
council_id <- read_csv(here("data_clean/council_id.csv"))


# Create vectors of all health board/local council id numbers
# These can then be used in filtering out data
health_vector <- health_board_id %>% 
  pull(hb_code)

council_vector <- council_id %>% 
  pull(la_code)
```


# Analysis of antenatal smoking
```{r}
smokers <- read_csv(here("data_clean/antenatal_smoking.csv")) 
```

```{r}
# Plot percentage of smokers - all Scotland
smokers_scotland <- smokers %>% 
  filter(feature_code == "S92000003") %>% 
  ggplot() +
  aes(x = year,
      y = smoker_ratio) +
  geom_point() +
  scale_x_continuous(breaks = 2002:2019) +
  scale_y_continuous(limits = c(0, NA)) +
  geom_smooth(method=lm , color="grey", se = FALSE) +
  labs(x = "Year",
       y = "Percentage of antenatal smokers",
       title = "Fewer new mothers in Scotland are smokers") +
  theme_minimal()

smokers_scotland

```


```{r}
# Plot percentage of smokers - individual council data
# Can have a dropdown selector in the dashboard to filter on feature_code
# so that we can select individual council areas
smokers_council <- smokers %>% 
  # example of filter:
  # filter(feature_code == "S12000041") %>% 
ggplot() +
  aes(x = year,
      y = smoker_ratio) +
  geom_point() +
  scale_x_continuous(breaks = 2002:2019) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(x = "Year",
       y = "Percentage of antenatal smokers",
       title = "Antenatal smokers") +
  theme_minimal()

smokers_council
```



# Low birthweight analysis
```{r}
low_birthweight <- read_csv(here("data_clean/low_birthweight.csv")) %>% 
 left_join(smokers,
            by = c("feature_code", "year")) 
```

```{r}
# Plot percentage of low birthweights - all Scotland
low_birthweight %>% 
  filter(feature_code == "S92000003") %>% 
  ggplot() +
  aes(x = year,
      y = weight_ratio) +
  geom_point() +
  geom_smooth(method=lm , color="grey", se = FALSE) +
  labs(x = "Year",
       y = "Percentage of low-weight births",
       title = "Fewer newborns in Scotland are being classified as having low birthweight")
```

```{r}
# Plot percentage of low birthweights - individual council data
# Can have a dropdown selector in the dashboard to filter on feature_code
# so that we can select individual council areas
low_birthweight %>% 
  # example of filter:
  # filter(feature_code == "S12000041") %>% 
  ggplot() +
  aes(x = year,
      y = weight_ratio,) +
  geom_point() +
  labs(x = "Year",
       y = "Percentage of low-weight births",
       title = "title")
```


```{r}
# Plot birthweight/smoking over time - all Scotland
low_birthweight %>% 
  filter(feature_code == "S92000003") %>% 
  ggplot() +
  aes(x = year, 
      y = smoker_ratio,
      size = weight_ratio
     ) +
  geom_point() +
  #geom_smooth(method=lm , color="red", se = FALSE) +
  labs(x = "Year",
       y = "% smoking",
       size = "% of births classed as low birthweight",
       title = "How have smoking and low birthweights in Scotland changed over time?") 
 
```


Older mother analysis
```{r}
mothers_ages <- read_csv(here("data_clean/mothers_ages.csv")) %>% 
  mutate(year = as.character(year))
```

```{r}
# Plot age band of first time mothers: Scotland
mothers_ages%>% 
  filter(feature_code == "S92000003") %>% 
  ggplot() +
  aes(x = year,
      y = ratio,
      group = age_band,
      colour = age_band) +
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks = 2002:2019) +
  scale_y_continuous(limits = c(0, NA)) +
#  geom_smooth(method=lm , color="red", se = FALSE) +
  labs(x = "Year",
       y = "Percentage of first-time mothers",
       title = "Are first-time mothers in Scotland getting older?")

```

```{r}
# Plot age band of first time mothers: all council areas
# This chart will not work unless there is a filter on feature_code
mothers_ages%>% 
  ggplot() +
  aes(x = year,
      y = ratio,
      group = age_band,
      colour = age_band) +
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks = 2002:2019) +
  scale_y_continuous(limits = c(0, NA)) +
#  geom_smooth(method=lm , color="red", se = FALSE) +
  labs(x = "Year",
       y = "Percentage of first-time mothers",
       title = "Are first-time mothers in Scotland getting older?")
```




# Age vs low-birthweight
```{r}
low_birthweight <- low_birthweight %>% 
  left_join(mothers_ages,
            by = c("year", "feature_code")) %>% 
  rename(older_ratio = ratio)
```

```{r}
low_birthweight %>% 
  filter(feature_code == "S92000003") %>% 
  ggplot() +
  aes(x = older_ratio,
      y = weight_ratio,) +
  geom_point() +
  geom_smooth(method=lm , color="red") +
  labs(x = "Percentage of first-time mothers",
       y = "Percentage of low-weight births",
       title = "Is there a relationship between low birthweight and mother's age?",
       subtitle = "Plot of low birthweight % vs mothers age band %, Scotland 2002 - 2019") +
  facet_wrap(~ age_band)
```
```{r}
low_birthweight %>% 
  filter(feature_code == "S92000003") %>% 
  ggplot() +
  aes(x = year,
      y = older_ratio,
      size = weight_ratio) +
  geom_point() +
 # geom_smooth(method=lm , color="red") +
  labs(x = "Year",
       y = "Percentage of first-time mothers aged 35+",
       title = "Is there a relationship between low birthweight and mother's age?",
       subtitle = "Plot of low birthweight % vs older mothers %, Scotland 2002 - 2019",
       size = "% low birthweight") +
  facet_wrap(~ age_band)
```




```{r}
breastfeeding <- read_csv(here("data_clean/breastfeeding.csv")) 

```

```{r}
breastfeeding %>% 
  filter(feature_code == "S92000003") %>% 
  ggplot() +
  aes(x = year,
      y = feeding_ratio) +
  geom_point() +
  scale_x_continuous(breaks = 2002:2019) +
  scale_y_continuous(limits = c(0, NA)) +
  geom_smooth(method=lm , color="red", se = FALSE) +
  labs(x = "Year",
       y = "Percentage of babies breastfed",
       title = "Are more babies being breastfed?")
```

```{r}
# bmi_scotland <- read_csv(here("data_clean/bmi_clinical.csv")) %>% 
#   filter(weight_category == "Clinical - Overweight, Obese & Severely Obese") %>% 
#   filter(hb_name == "Scotland",
#          gender == "All",
#          measurement == "Ratio")  %>% 
#   rename(bmi_ratio = value)

```

```{r}
# bmi_scotland %>% 
#   ggplot() +
#   aes(x = year,
#       y = bmi_ratio) +
#   scale_x_continuous(breaks = 2002:2019) +
#   scale_y_continuous(limits = c(0, NA)) +
#   geom_line() +
#   labs(x = "Year",
#        y = "% Overweight / Obese / Severely Obese",
#        title = "How many Primary 1 children have high BMI?",
#        subtitle = "Children in Scotland, 2002 - 2019")
```

```{r}
# bmi_healthboard <- read_csv(here("data_clean/bmi_clinical.csv")) %>% 
#   filter(weight_category == "Clinical - Overweight, Obese & Severely Obese") %>% 
#   filter(hb_name != "Scotland",
#          gender == "All",
#          measurement == "Ratio")  %>% 
#   rename(bmi_ratio = value)
```

```{r}
# bmi_healthboard %>% 
#   ggplot() +
#   aes(x = year,
#       y = bmi_ratio) +
#   scale_y_continuous(limits = c(0, NA)) +
#   geom_line() +
#   labs(x = "Year",
#        y = "% Overweight / Obese / Severely Obese",
#        title = "How many Primary 1 children have high BMI?",
#        subtitle = "Children in Scotland, 2002 - 2019"
#        ) +
#   facet_wrap(~ hb_name)
```




```{r}
dental_health <- read_csv(here("data_clean/dentalhealth.csv"))
```

```{r}
dental_health %>% 
  filter(feature_code == "S92000003") %>% 
  ggplot() +
  aes(x = year,
      y = dental_ratio) +
  geom_line() +
  geom_point() +
  labs(x = "Year",
       y = "% of P1 children with no obvious tooth decay",
       title = "Has children's dental health improved?")
```



