---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(sf)
library(rmapshaper)
library(here)
library(leaflet)
library(htmltools)
```

```{r}
scotland <- read_sf(here("data_raw/SG_NHS_HealthBoards_2019/SG_NHS_HealthBoards_2019.shp"))
```

```{r}
class(scotland)
```

```{r}
head(scotland, 14)
```

```{r}
scotland_geometry <- st_geometry(scotland)

scotland_geometry
```

```{r}
scotland_simple <- ms_simplify(scotland)
```

```{r}
plot(scotland_simple)
```



```{r}
alcohol <- read_csv("../data_clean/alcohol.csv") %>% 
  filter(sex == "All") %>% 
  filter(date_code == "2016-2019") %>% 
  filter(alcohol_consumption == "Hazardous/Harmful drinker")

alcohol_scotland_simple <- scotland_simple %>% 
  left_join(alcohol, by = c("HBCode" = "feature_code")) 
ggplot(alcohol_scotland_simple) +
  geom_sf(aes(group = hb_name, fill = value)) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), axis.text = element_blank()) +
  ggtitle("Alcohol Consumption in Scotland") + 
  scale_fill_gradient(low = "green", high = "red")

alcohol_scotland_simple %>% 
  leaflet() %>% 
  addTiles() %>%
  addMarkers(lng = ~longitude,
                   lat = ~latitude,
             popup = ~HBName)
```

```{r}
obesity <- read_csv("../data_clean/obesity.csv") %>% 
  filter(sex == "All") %>% 
  filter(date_code == "2016-2019") %>% 
  filter(obesity == "Obese")

scotland_simple %>% 
  left_join(obesity, by = c("HBCode" = "feature_code")) %>% 
ggplot() +
  geom_sf(aes(group = hb_name, fill = value)) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), axis.text = element_blank()) +
  ggtitle("Obesity in Scotland") + 
  scale_fill_gradient(low = "green", high = "red")
```

```{r}
smoking_status <- read_csv("../data_clean/smoking_status.csv") %>% 
  filter(sex == "All") %>% 
  filter(date_code == "2016-2019") %>% 
  filter(smoking_status == "Current smoker")

scotland_simple %>% 
  left_join(smoking_status, by = c("HBCode" = "feature_code")) %>% 
ggplot() +
  geom_sf(aes(group = hb_name, fill = value)) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), axis.text = element_blank()) +
  ggtitle("Smoking Status in Scotland") + 
  scale_fill_gradient(low = "green", high = "red")
```

```{r}
e_cig <- read_csv("../data_clean/e_cig.csv") %>% 
  filter(sex == "All") %>% 
  filter(date_code == "2016-2019") %>% 
  filter(e_cigarette_use == "Currently using")

scotland_simple %>% 
  left_join(e_cig, by = c("HBCode" = "feature_code")) %>% 
ggplot() +
  geom_sf(aes(group = hb_name, fill = value)) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), axis.text = element_blank()) +
  ggtitle("E-cigarette use in Scotland") + 
  scale_fill_gradient(low = "green", high = "red")
```

```{r}
alcohol %>% 
  filter(sex == "All") %>% 
  filter(hb_name == "Scotland") %>% 
    filter(date_code == "2016-2019") %>% 
  filter(alcohol_consumption == "Hazardous/Harmful drinker") 

alcohol_scotland


  select(value) %>% 
  pull()
```

```{r}
obesity_scotland <- read_csv("../data_clean/obesity.csv") %>% 
  filter(sex == "All") %>% 
  filter(hb_name == "Scotland") %>% 
    filter(date_code == "2016-2019") %>% 
  filter(obesity == "Obese")

obesity_scotland
```

```{r}

alcohol %>%
                    filter(sex == "All" | date_code == "2016-2019") %>%
                    filter(hb_name == "Scotland") %>%
                    filter(alcohol_consumption == "Hazardous/Harmful drinker") %>%
                    select(value) %>%
                    pull()
```


```{r}
smoking_status_scotland <- read_csv("../data_clean/smoking_status.csv") %>% 
  filter(sex == "All") %>% 
  filter(hb_name == "Scotland") %>% 
    filter(date_code == "2016-2019") %>% 
  filter(smoking_status == "Current smoker")

smoking_status_scotland
```

```{r}
e_cig_scotland <- read_csv("../data_clean/e_cig.csv") %>% 
  filter(sex == "All") %>% 
  filter(hb_name == "Scotland") %>% 
    filter(date_code == "2016-2019") %>% 
  filter(e_cigarette_use == "Currently using")

e_cig_scotland
```

```{r}
unique (obesity$sex)
                
                selectInput("year_selection",
                            "Year Selection",
                            choices = unique(obesity$date_code))

```

```{r}
alcohol %>%
                    filter(sex == "All" , date_code == "2016-2019") %>%
                    filter(hb_name == "Scotland") %>%
                    filter(alcohol_consumption == "Hazardous/Harmful drinker")
```

